<a href="https://colab.research.google.com/github/altamash00777/Development-of-AI-Response-Validation-System-with-Hallucination-Detection-Assistance/blob/main/Sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3

conn = sqlite3.connect("college.db")
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE IF NOT EXISTS students (
    id INTEGER PRIMARY KEY,
    name TEXT,
    department TEXT,
    marks INTEGER
)
""")

conn.commit()
print("Table created successfully!")

Table created successfully!

In [2]:
cursor.executemany("""
INSERT INTO students (id, name, department, marks)
VALUES (?, ?, ?, ?)
""", [
    (1, "Aman", "CSE", 85),
    (2, "Sara", "IT", 92),
    (3, "Rahul", "CSE", 78),
    (4, "Priya", "ECE", 88),
    (5, "Vikas", "IT", 65)
])

conn.commit()
print("Data inserted!")

Data inserted!

In [3]:
cursor.execute("SELECT * FROM students")
print(cursor.fetchall())

[(1, 'Aman', 'CSE', 85), (2, 'Sara', 'IT', 92), (3, 'Rahul', 'CSE', 78), (4, 'Priya', 'ECE', 88), (5, 'Vikas', 'IT', 65)]

In [4]:
cursor.execute("SELECT * FROM students WHERE marks > 80")
print(cursor.fetchall())

[(1, 'Aman', 'CSE', 85), (2, 'Sara', 'IT', 92), (4, 'Priya', 'ECE', 88)]

In [5]:
cursor.execute("""
    SELECT name, marks
    FROM students
    ORDER BY marks DESC
""")
print(cursor.fetchall())

[('Sara', 92), ('Priya', 88), ('Aman', 85), ('Rahul', 78), ('Vikas', 65)]

In [6]:
cursor.execute("""
    SELECT department, AVG(marks)
    FROM students
    GROUP BY department
""")
print(cursor.fetchall())

[('CSE', 81.5), ('ECE', 88.0), ('IT', 78.5)]

In [7]:
import pandas as pd

df = pd.read_sql_query(
    "SELECT * FROM students",
    conn
)

display(df)

   id   name department  marks
0   1   Aman        CSE     85
1   2   Sara         IT     92
2   3  Rahul        CSE     78
3   4  Priya        ECE     88
4   5  Vikas         IT     65

In [8]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("college.db")

cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS students (
    id INTEGER PRIMARY KEY,
    name TEXT,
    department TEXT,
    marks INTEGER
)
""")

# Insert sample data only if the table is empty
if cursor.execute("SELECT COUNT(*) FROM students").fetchone()[0] == 0:
    cursor.executemany("""
        INSERT INTO students (id, name, department, marks)
        VALUES (?, ?, ?, ?)
    """, [
        (1, "Aman", "CSE", 85),
        (2, "Sara", "IT", 92),
        (3, "Rahul", "CSE", 78),
        (4, "Priya", "ECE", 88),
        (5, "Vikas", "IT", 65),
        (6, "Neha", "CSE", 92),
        (7, "Rohan", "ECE", 72)
    ])
    conn.commit()

display(pd.read_sql_query("SELECT * FROM students", conn))

   id   name department  marks
0   1   Aman        CSE     85
1   2   Sara         IT     92
2   3  Rahul        CSE     78
3   4  Priya        ECE     88
4   5  Vikas         IT     65

In [9]:
# sql queries
def run_sql(query):
    display(pd.read_sql_query(query, conn))

In [10]:
# where clause
run_sql("""
SELECT *
FROM students
WHERE marks > 80
""")

   id   name department  marks
0   1   Aman        CSE     85
1   2   Sara         IT     92
2   4  Priya        ECE     88

In [11]:
# -- Marks greater than or equal to 85
# SELECT * FROM students WHERE marks >= 85;

# -- Students from CSE
# SELECT * FROM students WHERE department = 'CSE';

# -- Students who scored less than 80
# SELECT * FROM students WHERE marks < 80;

# -- Students who are not from CSE
# SELECT * FROM students WHERE department != 'CSE';

In [12]:
run_sql("""
SELECT DISTINCT department
FROM students
""")

  department
0        CSE
1         IT
2        ECE

In [14]:
# SELECT DISTINCT department, marks
# FROM students;

In [15]:
# and or not
run_sql("""
SELECT *
FROM students
WHERE department = 'CSE' AND marks > 80
""")

   id  name department  marks
0   1  Aman        CSE     85

In [16]:
# between
run_sql("""
SELECT *
FROM students
WHERE marks BETWEEN 70 AND 90
""")

   id   name department  marks
0   1   Aman        CSE     85
1   3  Rahul        CSE     78
2   4  Priya        ECE     88

In [17]:
# in
run_sql("""
SELECT *
FROM students
WHERE department IN ('CSE', 'ECE')
""")

   id   name department  marks
0   1   Aman        CSE     85
1   3  Rahul        CSE     78
2   4  Priya        ECE     88

In [18]:
# -- Names starting with A
# SELECT * FROM students WHERE name LIKE 'A%';

# -- Names ending with a
# SELECT * FROM students WHERE name LIKE '%a';

# -- Names containing 'ha'
# SELECT * FROM students WHERE name LIKE '%ha%';

In [19]:
# aggregrate function
run_sql("""
SELECT
    AVG(marks) AS average_marks,
    MAX(marks) AS highest_marks,
    MIN(marks) AS lowest_marks,
    SUM(marks) AS total_marks,
    COUNT(*) AS total_students
FROM students
""")

   average_marks  highest_marks  lowest_marks  total_marks  total_students
0           81.6             92            65          408               5

In [20]:
# group by and having
run_sql("""
SELECT department, AVG(marks) AS average_marks
FROM students
GROUP BY department
HAVING AVG(marks) > 80
""")

  department  average_marks
0        CSE           81.5
1        ECE           88.0